/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as PreferencesRouteImport } from './routes/preferences'
import { Route as ContributeIndexRouteImport } from './routes/contribute.index'
import { Route as FacilityIdRouteImport } from './routes/facility.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferencesRoute = PreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributeIndexRoute = ContributeIndexRouteImport.update({
  id: '/contribute/',
  path: '/contribute/',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilityIdRoute = FacilityIdRouteImport.update({
  id: '/facility/$id',
  path: '/facility/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/preferences': typeof PreferencesRoute
  '/facility/$id': typeof FacilityIdRoute
  '/contribute/': typeof ContributeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/preferences': typeof PreferencesRoute
  '/facility/$id': typeof FacilityIdRoute
  '/contribute': typeof ContributeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/discover': typeof DiscoverRoute
  '/preferences': typeof PreferencesRoute
  '/facility/$id': typeof FacilityIdRoute
  '/contribute/': typeof ContributeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/discover' | '/preferences' | '/facility/$id' | '/contribute/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/discover' | '/preferences' | '/facility/$id' | '/contribute'
  id:
    | '__root__'
    | '/'
    | '/discover'
    | '/preferences'
    | '/facility/$id'
    | '/contribute/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiscoverRoute: typeof DiscoverRoute
  PreferencesRoute: typeof PreferencesRoute
  FacilityIdRoute: typeof FacilityIdRoute
  ContributeIndexRoute: typeof ContributeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preferences': {
      id: '/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof PreferencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contribute/': {
      id: '/contribute/'
      path: '/contribute'
      fullPath: '/contribute/'
      preLoaderRoute: typeof ContributeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facility/$id': {
      id: '/facility/$id'
      path: '/facility/$id'
      fullPath: '/facility/$id'
      preLoaderRoute: typeof FacilityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiscoverRoute: DiscoverRoute,
  PreferencesRoute: PreferencesRoute,
  FacilityIdRoute: FacilityIdRoute,
  ContributeIndexRoute: ContributeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
